---
- name: "Install pip"
  pkgng:
    name: "py{{ python_nodotversion }}-pip"
    state: "present"

- name: "Install setuptools"
  pkgng:
    name: "py{{ python_nodotversion }}-setuptools"
    state: "present"

- name: "Install requirements.txt modules with pip. Install in the global py env."
  pip:
    requirements: "{{ nipap_checkout_path }}/nipap/requirements.txt"

