---
- name: "Install bind"
  pkgng:
    name: "{{ bind_package }}"
    state: "present"

- name: "Install bind config file"
  template:
    src: "named.conf.j2"
    dest: "/usr/local/etc/namedb/named.conf"
    mode: "0644"
    #validate: "/usr/local/sbin/named-checkconf %s"
  notify: "reload bind"
  tags: "bindconfig"

- name: "Install bind automatic zones file"
  template:
    src: "named-zones.conf.j2"
    dest: "/usr/local/etc/namedb/named-zones.conf"
    mode: "0644"
    #validate: "/usr/local/sbin/named-checkconf %s"
  notify: "reload bind"
  tags: "bindconfig"

- name: "Create dynamic zonefiles"
  template:
    src: "named-dynamic-zone.j2"
    dest: "/usr/local/etc/namedb/dynamic/{{ item['zone'] }}.zone"
    mode: "0644"
    owner: "bind"
    group: "bind"
    force: no
  with_items: "{{ bind_dynamic_zonelist | default([]) }}"
  notify: "reload bind"
  tags: "bindconfig"
