---
- name: "Install bind_exporter"
  pkgng:
    name: "bind_exporter"
    state: "present"

- name: "Create supervisord.d config file to run bind_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "bind_exporter"
    supervisord_programs:
      - name: "bind_exporter"
        comment: "run prometheus bind_exporter"
        command: "/usr/local/bin/bind_exporter --bind.stats-url {{  bind_statsurl }} --bind.stats-groups 'server,view,tasks'"
        user: "0"
    supervisord_extra_programs: []

- name: "Create exporter_exporter.d config file for bind_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "bind_exporter.yml"
    expexp_program:
      method: "http"
      http:
        port: 9119
