---
- name: "Install bind 9.11"
  pkgng:
    name: "bind911"
    state: "present"

- name: "Install bind config file"
  template:
    src: "named.conf.j2"
    dest: "/usr/local/etc/namedb/named.conf"
    mode: "0644"
    #validate: "/usr/local/sbin/named-checkconf %s"
  notify: "reload bind"
  tags: "bindconfig"

- name: "Install bind automatic zones file"
  template:
    src: "named-zones.conf.j2"
    dest: "/usr/local/etc/namedb/named-zones.conf"
    mode: "0644"
    #validate: "/usr/local/sbin/named-checkconf %s"
  notify: "reload bind"
  tags: "bindconfig"

- name: "Create dynamic zonefiles"
  template:
    src: "named-dynamic-zone.j2"
    dest: "/usr/local/etc/namedb/dynamic/{{ item['zone'] }}.zone"
    mode: "0644"
    owner: "bind"
    group: "bind"
    force: no
  with_items: "{{ bind_dynamic_zonelist | default([]) }}"
  notify: "reload bind"
  tags: "bindconfig"

- name: "Add dampening stats script"
  copy:
    src: "bind_dampening_stats.sh"
    dest: "/usr/local/bin/bind_dampening_stats.sh"
  notify: "restart bind_dampening_stats"
  when: bind_dampening

- name: "Create supervisord.d config to run bind_dampening_stats.sh"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "bind_dampening_stats"
    supervisord_programs:
      - name: "bind_dampening_stats"
        comment: "run bind_dampening_stats"
        command: "/usr/local/bin/bind_dampening_stats.sh"
        user: "0"
  when: bind_dampening
