---
- include_tasks:
    file: "bind.yml"
    apply:
      tags:
        - "bind"
        - "bindconfig"
  tags:
    - "bind"
    - "bindconfig"
- include_tasks:
    file: "rndc.yml"
    apply:
      tags:
        - "bind"
  tags:
    - "bind"
- include_tasks:
    file: "syslog.yml"
    apply:
      tags:
        - "bind"
  tags:
    - "bind"
- include_tasks:
    file: "newsyslog.yml"
    apply:
      tags:
        - "bind"
  tags:
    - "bind"
- include_tasks:
    file: "supervisord.yml"
    apply:
      tags:
        - "bind"
  tags:
    - "bind"
- include_tasks:
    file: "bind_exporter.yml"
    apply:
      tags:
        - "bind"
        - "bindexp"
  tags:
    - "bind"
    - "bindexp"
