---
- name: "Create supervisord.d config file to run bind"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "bind"
    supervisord_programs:
      - name: "bind"
        comment: "run bind"
        command: "/usr/local/sbin/named -f -u bind -c /usr/local/etc/namedb/named.conf"
        user: "0"

