---
- name: "add syslog.d config for bind"
  copy:
    src: "bind-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/bind.conf"
  notify: "restart syslogd"

- name: "Make sure /var/log/bind-default.log exists"
  copy:
    dest: "/var/log/bind-default.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

- name: "Make sure /var/log/bind-general.log exists"
  copy:
    dest: "/var/log/bind-general.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

- name: "Make sure /var/log/bind-security.log exists"
  copy:
    dest: "/var/log/bind-security.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

- name: "Make sure /var/log/bind-dampening.log exists"
  copy:
    dest: "/var/log/bind-dampening.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

- name: "Make sure /var/log/bind-queries.log exists"
  copy:
    dest: "/var/log/bind-queries.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"
  when: bind_querylog
