---
- name: "Install charybdis"
  pkgng:
    name: "charybdis"
    state: "present"

- name: "Create charybdis logfile directory"
  file:
    path: "/var/log/charybdis"
    state: "directory"
    owner: "ircd"
    group: "ircd"
    mode: "0755"

- name: "Create charybdis database directory"
  file:
    path: "/var/db/charybdis"
    state: "directory"
    owner: "ircd"
    group: "ircd"
    mode: "0755"

