---
- name: "Create supervisord.d config file to run charybdis"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "charybdis"
    supervisord_programs:
      - name: "charybdis"
        comment: "run charybdis"
        command: "/usr/local/bin/ircd -foreground -configfile /usr/local/etc/charybdis/ircd.conf"
        user: "ircd"

