---
- name: "Include any pf_vars.yml file that may exist"
  include_vars:
    file: "../include_vars/pf_vars.yml"
  ignore_errors: yes
  tags:
    - "pf"

- name: "Setup pf.conf for jail/vm hosts"
  template:
    src: "pf-jail.conf.j2"
    dest: "{{ pf_conf_path }}"
    validate: 'pfctl -n -f %s'
  when: pf_jail_vm_host
  notify: "reload pf"
  tags:
    - "pf"

- name: "Setup pf.conf for regular hosts and gateways"
  template:
    src: "pf.conf.j2"
    dest: "{{ pf_conf_path }}"
    validate: 'pfctl -n -f %s'
  when:
    - pf_jail_vm_host is not defined
    - pf_anycast_host is not defined
  notify: "reload pf"
  tags:
    - "pf"

- name: "Setup pf.conf for anycast hosts"
  template:
    src: "pf-anycast.conf.j2"
    dest: "{{ pf_conf_path }}"
    validate: 'pfctl -n -f %s'
  when: pf_anycast_host
  notify: "reload pf"
  tags:
    - "pf"

- name: "Enable pf"
  service:
    name: "pf"
    enabled: yes
  notify:
    - "kldload pf module"
  tags:
    - "pf"

- name: "Enable pflog"
  service:
    name: "pflog"
    enabled: yes
  notify:
    - "kldload pflog module"
  tags:
    - "pf"

