---
- name: "Install prometheus"
  pkgng:
    name: "prometheus"
    state: "present"

- name: "Make sure prometheus data directory exists"
  file:
    path: "/var/db/prometheus"
    state: "directory"
    owner: "prometheus"
    group: "prometheus"
    mode: "0755"

- name: "Install Prometheus config"
  template:
    src: "prometheus.yml.j2"
    dest: "/usr/local/etc/prometheus.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  tags:
    - "promconf"
  notify:
    - "restart prometheus"

- name: "Install Prometheus rules config"
  template:
    src: "prometheus-rules.yml.j2"
    dest: "/usr/local/etc/prometheus-rules.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  tags:
    - "promconf"
  notify:
    - "restart prometheus"

- name: "Install Prometheus web.yml config"
  template:
    src: "prometheus-web.yml.j2"
    dest: "/usr/local/etc/prometheus-web.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  tags:
    - "promconf"
  notify:
    - "restart prometheus"

- name: "Make sure prometheus targets directory exists"
  file:
    path: "/usr/local/etc/prometheus"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"

