---
- name: "Install powerdns auth"
  pkgng:
    name: "powerdns"
    state: "present"

- name: "Install pdns.conf"
  template:
    source: "pdns.conf.j2"
    dest: "/usr/local/etc/pdns/pdns.conf"
    mode: "0600"
