---
- name: "Include host secrets"
  hosts: "all"
  tasks:
    - name: "Check if host secrets exists for in host_vars"
      local_action: stat path="/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
      register: stat_result
      tags:
        - "always"
    - name: "Include host secrets when the file exists"
      include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
      tags:
        - "always"
      when: stat_result.stat.exists

- name: "Include group secrets"
  hosts: "all"
  tasks:
    - name: "Check if group secrets exists in group_vars for any group this host is a member of"
      local_action: stat path="/usr/local/etc/ansible/group_vars/{{ item }}-secrets.yml"
      tags:
        - "always"
      loop: "{{ group_names }}"
      register: result
    - name: "Include group secrets when the file exists"
      include_vars: "{{ item.stat.path }}"
      tags:
        - "always"
      when: item.stat.exists
      loop: "{{ result.results }}"

- name: "Include include_vars/global.yml if available"
  hosts: "all"
  tasks:
    - include_vars: "/usr/local/etc/ansible/roles/include_vars/global.yml"
      ignore_errors: yes
      tags:
        - "always"

- name: "configure basic freebsd stuff on all hosts (yes this means only freebsd for now)"
  hosts: "all"
  become: yes
  roles:
    - "freebsd_base"

- name: "configure freebsd hosts (physical servers)"
  hosts: "freebsd_hosts"
  become: yes
  roles:
    - "freebsd_host"

- name: "configure ezjail hosts"
  hosts: "ezjail_hosts"
  become: yes
  roles:
    - "ezjail_host"

- name: "configure chyves bhyve hosts"
  hosts: "chyves_hosts"
  become: yes
  roles:
    - "chyves_host"

##############################################################################
### application roles below here

- name: "configure etherpad servers"
  hosts: "etherpad_servers"
  become: yes
  roles:
    - "etherpad_server"

- name: "configure all murmur servers"
  hosts: "murmur_servers"
  become: yes
  roles:
    - "murmur_server"

- name: "configure all nginx http and https servers"
  hosts: "nginx_servers"
  become: yes
  roles:
    - "nginx_server"

- name: "configure dovecot servers"
  hosts: "dovecot_servers"
  become: yes
  roles:
    - "dovecot_server"

- name: "configure erlang webservers"
  hosts: "erlang_web_servers"
  become: yes
  roles:
    - "erlang_web_server"

- name: "configure wiki servers"
  hosts: "mediawiki_servers"
  become: yes
  roles:
    - "mediawiki_server"

- name: "configure people servers"
  hosts: "people_servers"
  become: yes
  roles:
    - "people_server"

- name: "configure postfix servers"
  hosts: "postfix_servers"
  become: yes
  roles:
    - "postfix_server"

- name: "configure tor servers"
  hosts: "tor_servers"
  become: yes
  roles:
    - "tor_server"

- name: "configure kea dhcp servers"
  hosts: "kea_servers"
  become: yes
  roles:
    - "kea_server"

- name: "configure znc servers"
  hosts: "znc_servers"
  become: yes
  roles:
    - "znc_server"

- name: "configure isc dhcp servers"
  hosts: "isc_dhcpd_servers"
  become: yes
  roles:
    - "isc_dhcpd_server"

- name: "configure metabase servers"
  hosts: "metabase_servers"
  become: yes
  roles:
    - "metabase_server"

- name: "configure certgrinder servers"
  hosts: "certgrinder_servers"
  become: yes
  roles:
    - "certgrinder_server"

- name: "configure charybdis ircd servers"
  hosts: "charybdis_servers"
  become: yes
  roles:
    - "charybdis_server"

- name: "configure PostgreSQL servers"
  hosts: "postgresql_servers"
  become: yes
  roles:
    - "postgresql_server"

- name: "configure Unbound servers"
  hosts: "unbound_servers"
  become: yes
  roles:
    - "unbound_server"

- name: "configure syslog-ng servers"
  hosts: "syslogng_servers"
  become: yes
  roles:
    - "syslogng_server"

- name: "configure zabbix servers"
  hosts: "zabbix_servers"
  become: yes
  roles:
    - "zabbix_server"

- name: "configure zabbix frontend servers"
  hosts: "zabbix_frontend_servers"
  become: yes
  roles:
    - "zabbix_frontend_server"

- name: "configure zabbix proxy servers"
  hosts: "zabbix_proxy_servers"
  become: yes
  roles:
    - "zabbix_proxy_server"

- name: "configure tykdnscheck servers"
  hosts: "tykdnscheck_servers"
  become: yes
  roles:
    - "tykdnscheck_server"

- name: "configure roundcube servers"
  hosts: "roundcube_servers"
  become: yes
  roles:
    - "roundcube_server"

- name: "configure nfsen servers"
  hosts: "nfsen_servers"
  become: yes
  roles:
    - "nfsen_server"

- name: "configure tykbackup servers"
  hosts: "tykbackup_servers"
  become: yes
  roles:
    - "tykbackup_server"

- name: "configure download servers"
  hosts: "download_servers"
  become: yes
  roles:
    - "download_server"

- name: "configure rt servers"
  hosts: "rt_servers"
  become: yes
  roles:
    - "rt_server"

- name: "configure radicale servers"
  hosts: "radicale_servers"
  become: yes
  roles:
    - "radicale_server"

- name: "configure elk servers"
  hosts: "elk_servers"
  become: yes
  roles:
    - "elk_server"

- name: "configure iperf servers"
  hosts: "iperf_servers"
  become: yes
  roles:
    - "iperf_server"

- name: "configure bind servers"
  hosts: "bind_servers"
  become: yes
  roles:
    - "bind_server"

- name: "configure prometheus servers"
  hosts: "prometheus_servers"
  become: yes
  roles:
    - "prometheus_server"

- name: "configure grafana servers"
  hosts: "grafana_servers"
  become: yes
  roles:
    - "grafana_server"

- name: "configure ansible servers"
  hosts: "ansible_servers"
  become: yes
  roles:
    - "ansible_server"

- name: "configure django channels2 servers"
  hosts: "django_channels2_servers"
  become: yes
  roles:
    - "django_channels2_server"

- name: "configure nipapd servers"
  hosts: "nipapd_servers"
  become: yes
  roles:
    - "nipapd_server"

- name: "configure nipapcli servers"
  hosts: "nipapcli_servers"
  become: yes
  roles:
    - "nipapcli_server"

- name: "configure nipapwww servers"
  hosts: "nipapwww_servers"
  become: yes
  roles:
    - "nipapwww_server"

- name: "configure speedtest servers"
  hosts: "speedtest_servers"
  become: yes
  roles:
    - "speedtest_server"

- name: "configure mastodon servers"
  hosts: "mastodon_servers"
  become: yes
  roles:
    - "mastodon_server"

- name: "configure freeradius3 servers"
  hosts: "freeradius_servers"
  become: yes
  roles:
    - "freeradius_server"

- name: "configure alertmanager servers"
  hosts: "alertmanager_servers"
  become: yes
  roles:
    - "alertmanager_server"

- name: "configure searx servers"
  hosts: "searx_servers"
  become: yes
  roles:
    - "searx_server"

- name: "configure blackbox exporter servers"
  hosts: "blackbox_exporter_servers"
  become: yes
  roles:
    - "blackbox_exporter_server"

- name: "configure nfs servers"
  hosts: "nfs_servers"
  become: yes
  roles:
    - "nfs_server"

- name: "configure snmp_exporter servers"
  hosts: "snmp_exporter_servers"
  become: yes
  roles:
    - "snmp_exporter_server"

- name: "configure poudriere servers"
  hosts: "poudriere_servers"
  become: yes
  roles:
    - "poudriere_server"

- name: "configure prosody servers"
  hosts: "prosody_servers"
  become: yes
  roles:
    - "prosody_server"

- name: "configure ctld servers"
  hosts: "ctld_servers"
  become: yes
  roles:
    - "ctld_server"

- name: "configure gitea servers"
  hosts: "gitea_servers"
  become: yes
  roles:
    - "gitea_server"

- name: "configure powerdns_recursor servers"
  hosts: "powerdns_recursor_servers"
  become: yes
  roles:
    - "powerdns_recursor_server"

- name: "configure dnsdist servers"
  hosts: "dnsdist_servers"
  become: yes
  roles:
    - "dnsdist_server"

- name: "configure atheme servers"
  hosts: "atheme_servers"
  become: yes
  roles:
    - "atheme_server"

- name: "configure openbgpd servers"
  hosts: "openbgpd_servers"
  become: yes
  roles:
    - "openbgpd_server"

- name: "configure prometheus monitored servers"
  hosts: "prometheus_monitored_servers"
  become: yes
  roles:
    - "prometheus_monitored_server"

