---
- name: "Make sure bird2 newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "bird2-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/bird2.conf"

