---
- include_tasks:
    file: "nginx.yml"
    apply:
      tags:
        - "nginx"
  tags:
    - "nginx"
- include_tasks:
    file: "syslog.yml"
    apply:
      tags:
        - "nginx"
  tags:
    - "nginx"
- include_tasks:
    file: "directories.yml"
    apply:
      tags:
        - "nginx"
  tags:
    - "nginx"
- include_tasks:
    file: "configs.yml"
    apply:
      tags:
        - "nginx"
        - "vhosts"
  tags:
    - "nginx"
    - "vhosts"
- include_tasks:
    file: "ocsp.yml"
    apply:
      tags:
        - "nginx"
  tags:
    - "nginx"
  when:
    - nginx_proxy
    - certgrinder_hostname_sets is defined
    - nginx_ocsp_stapling
- include_tasks:
    file: "goaccess.yml"
    apply:
      tags:
        - "nginx"
  tags:
    - "nginx"
  when:
    - nginx_goaccess
    - nginx_proxy
- include_tasks:
    file: "nginx_exporter.yml"
    apply:
      tags:
        - "nginx"
  tags:
    - "nginx"
