---
- include_tasks: "nginx.yml"
- include_tasks: "syslog.yml"
- include_tasks: "directories.yml"
- include_tasks: "configs.yml"
  tags:
    - "vhosts"
- include_tasks: "ocsp.yml"
  when:
    - nginx_proxy
    - certgrinder_hostname_sets is defined
    - nginx_ocsp_stapling
- include_tasks: "goaccess.yml"
  when:
    - nginx_goaccess
    - nginx_proxy
- include_tasks: "nginx_exporter.yml"
  when: "'prometheus_monitored_servers' in group_names"

