---
- name: "Install nginx"
  pkgng:
    name: "nginx"
    state: "present"

- name: "Enable nginx"
  service:
    name: "nginx"
    enabled: yes

- name: "Create certgrinder hooks.d file to restart nginx"
  include_role:
    name: "certgrinder_client"
    tasks_from: "certgrinder_hook.d"
  vars:
    hookname: "nginx"
    hookfile: |
      #!/bin/sh
      /usr/sbin/service nginx restart
