---
- name: "Add local7.none to the /var/log/messages line in /etc/syslog.conf to keep nginx logs out of that file"
  replace:
    dest: "/etc/syslog.conf"
    regexp: '^((?!.*?local7\.none).*)\s+/var/log/messages$'
    replace: '\1;local7.none	/var/log/messages'
  notify:
    - "restart syslogd"

- name: "Make sure nginx newsyslog config file exists"
  template:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "nginx-newsyslog.conf.j2"
    dest: "/usr/local/etc/newsyslog.conf.d/nginx.conf"

