---
- name: "Add certgrinder user"
  user:
    name: "{{ certgrinder_user }}"
    comment: "certgrinder user"

- name: "Remove existing SSH authorized_keys file"
  file:
    path: "/usr/home/{{ certgrinder_user }}/.ssh/authorized_keys"
    state: "absent"
  tags: "sshkeys"

- name: "Add ssh authorized_keys for all certgrinder clients"
  authorized_key:
    user: "{{ certgrinder_user }}"
    key: "{{ item.value.authkey }}"
    key_options: 'from="{{ item.value.fromip }}",command="~/certgrinder/csrgrinder",restrict'
  with_dict: "{{ certgrinder_authorized_keys | default({}) }}"
  tags: "sshkeys"

- name: "Add certgrinder user to sudoers (allow certbot)"
  lineinfile:
    dest: "/usr/local/etc/sudoers"
    state: "present"
    regexp: "^{{ certgrinder_user }} ALL=\\(ALL\\) NOPASSWD: /usr/local/bin/certbot$"
    line: "{{ certgrinder_user }} ALL=(ALL) NOPASSWD: /usr/local/bin/certbot"
    validate: "visudo -cf %s"

- name: "Add certgrinder user to sudoers (allow ACMEZONE and WEBROOT env. vars.)"
  lineinfile:
    dest: "/usr/local/etc/sudoers"
    state: "present"
    line: 'Defaults env_keep += "ACMEZONE WEBROOT"'
    validate: "visudo -cf %s"

