---
- name: "Add prometheus exporter user"
  user:
    name: "{{ prometheus_exporter_user }}"
    comment: "Prometheus exporter user"
    home: "/nonexistent"
    create_home: False

- name: "Install Go"
  pkgng:
    name: "go"
    state: "present"

- name: "Get source code for exporter_exporter"
  git:
    repo: "https://github.com/QubitProducts/exporter_exporter"
    dest: "/root/exporter_exporter"
    force: yes
    version: "{{ exporter_exporter_version }}"
  register: gitresult

- name: "Go get exporter_exporter"
  command: "go get ."
  args:
    chdir: "/root/exporter_exporter"
  environment:
    GOPATH: "/root/go"
    GOBIN: "/usr/local/bin"
  when: gitresult.changed

- name: "Create exporter_exporter.d config directory"
  file:
    path: "/usr/local/etc/exporter_exporter.d"
    state: "directory"

- name: "Create supervisord.d config file to run exporter_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "exporter_exporter"
    supervisord_programs:
      - name: "exporter_exporter"
        comment: "run exporter_exporter"
        command: "/usr/local/bin/exporter_exporter -config.file=/usr/local/etc/expexp.yml -config.dirs=/usr/local/etc/exporter_exporter.d -web.listen-address= -web.tls.listen-address={{ exporter_exporter_listen_address }} -web.tls.cert=/usr/home/certgrinder/certificates/{{ ansible_nodename }}-chain.rsa.crt -web.tls.key /usr/home/certgrinder/certificates/{{ ansible_nodename }}-keypair.rsa.key -web.proxy-path={{ exporter_exporter_proxy_path }} -web.telemetry-path={{ exporter_exporter_telemetry_path }}"
        user: "{{ prometheus_exporter_user }}"
    supervisord_extra_programs: []

