---
- name: "Check out extra_git_repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    force: yes
    version: "{{ item.version|default('main') }}"
  loop: "{{ extra_git_repos }}"
