---
- name: "Get source code for exporter_exporter"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    force: yes
    version: "{{ item.branch|default('main') }}"
  loop: "{{ extra_git_repos }}"
