---
- include_tasks: "debug.yml"
- include_tasks: "resolvconf.yml"
- include_tasks: "etchosts.yml"
- include_tasks: "pkg.yml"
  when: "poudriere_client"
  tags:
    - "pkgrepo"
- include_tasks: "python.yml"
- include_tasks: "packages.yml"
- include_tasks: "users.yml"
  tags:
    - "usermanagement"
- include_tasks: "ansible.yml"
  tags:
    - "ansiblekeys"
- include_tasks: "motd.yml"
- include_tasks: "sshd.yml"
- include_tasks: "syslog.yml"
- include_tasks: "resolvconf.yml"
- include_tasks: "etcaliases.yml"
- include_tasks: "postfixnullmailer.yml"
  when: "'postfix_servers' not in group_names"
- include_tasks: "newsyslog.yml"
- include_tasks: "extra-cron.d-jobs.yml"
- include_tasks: "networkinterfaces.yml"
  when: network_interfaces is defined
  tags:
    - "network"
- include_tasks: "static_routes.yml"
  when: static_routes is defined
  tags:
    - "routing"

