---
- include_tasks: "etchosts.yml"
- include_tasks: "pkg.yml"
  when: "poudriere_client"
  tags:
    - "pkgrepo"
- include_tasks: "packages.yml"
- include_tasks: "users.yml"
  tags:
    - "usermanagement"
- include_tasks: "ansible.yml"
  tags:
    - "ansiblekeys"
- include_tasks: "motd.yml"
- include_tasks: "resolvconf.yml"
- include_tasks: "sshd.yml"
- include_tasks: "syslog.yml"
- include_tasks: "resolvconf.yml"
- include_tasks: "etcaliases.yml"
- include_tasks: "postfixnullmailer.yml"
  when: "'postfix_servers' not in group_names"
- include_tasks: "newsyslog.yml"
- include_tasks: "extra-cron.d-jobs.yml"
- include_tasks: "stickybridge.yml"
  when: stickybridge_configs is defined
  tags:
    - "stickybridge"

