---
- name: "Disable sendmail"
  sysrc:
    name: "sendmail_enable"
    value: "none"
  register: disableresult

- name: "onestop sendmail when needed"
  command: "/usr/sbin/service sendmail onestop"
  ignore_errors: True
  when: disableresult is changed

- name: "Disable postfix"
  sysrc:
    name: "postfix_enable"
    value: "no"
  register: postfixresult

- name: "onestop postfix when needed"
  command: "/usr/sbin/service postfix onestop"
  ignore_errors: True
  when: postfixresult is changed

- name: "Uninstall postfix"
  pkgng:
    name: "postfix"
    state: "absent"
  when: postfixresult is changed

- name: "Install nullmailer"
  pkgng:
    name: "nullmailer"
    state: "present"

- name: "Create the nullmailer remotes file"
  template:
    src: "nullmailer-remotes.j2"
    dest: "/usr/local/etc/nullmailer/remotes"
  notify: "restart nullmailer"

- name: "write hostname to nullmailer me file"
  copy:
    content: "{{ ansible_host }}"
    dest: "/usr/local/etc/nullmailer/me"
    mode: "0644"
    owner: "root"
    group: "wheel"
  notify: "restart nullmailer"

- name: "Enable and start nullmailer"
  service:
    name: "nullmailer"
    enabled: yes
  notify: "start nullmailer"

- name: "create /usr/local/etc/mail/ if needed"
  file:
    path: "/usr/local/etc/mail/"
    state: directory
    mode: "755"
    owner: "root"
    group: "wheel"

- name: "activate nullmailer as mailer program"
  copy:
    src: "nullmailer.conf"
    dest: "/usr/local/etc/mail/mailer.conf"
    mode: "0644"
    owner: "root"
    group: "wheel"

- name: "postfix uninstalled email"
  mail:
    to: "{{ certgrinder_admin_email }}"
    subject: "postfix has been replaced with nullmailer on host {{ ansible_host }}"
    body: "Ansible has uninstalled postfix and installed nullmailer on host {{ ansible_host }}. Please run pkg autoremove on {{ ansible_host }} to clean up dependencies that are no longer needed."
  when: postfixresult is changed

