---
- name: "add syslog.d config for php-fpm"
  template:
    src: "php-fpm_syslogd.conf.j2"
    dest: "/usr/local/etc/syslog.d/php-fpm.conf"
  notify:
    - "restart syslogd"

- name: "Make sure php-fpm logfile exists"
  copy:
    dest: "{{ php_fpm_logfile_path }}"
    content: ""
    force: "no"
  notify:
    - "restart syslogd"

- name: "Make sure php-fpm newsyslog config file exists"
  template:
    src: "php-fpm_newsyslog.conf.j2"
    dest: "/usr/local/etc/newsyslog.conf.d/php-fpm.conf"

