---
- name: "Install getmail"
  pkgng:
    name: "getmail"
    state: "present"

- name: "add getmail user"
  user:
    name: "{{ getmail_user }}"
    comment: "getmail user"

- name: "Create getmail config directory"
  file:
    path: "/home/getmail/.getmail"
    state: "directory"
    owner: "getmail"
    group: "getmail"
    mode: "0700"

- name: "add getmail config files"
  template:
    src: "getmailrc.j2"
    dest: "{{ getmail_path }}/{{ item.filename }}{{ item.action }}rc"
    mode: "0600"
    owner: "{{ getmail_user }}"
    group: "{{ getmail_user }}"
  with_items: "{{ getmail_mailboxes | default([]) }}"

- name: "Enable cronjobs to run getmail"
  cron:
    name: "Run getmail for queue '{{ item.queuename }}' action '{{ item.action }}'"
    job: "/usr/local/bin/getmail --rcfile {{ getmail_path }}/{{ item.filename }}{{ item.action }}rc > /dev/null 2>&1"
    cron_file: "rt_getmail"
    user: "getmail"
  with_items: "{{ getmail_mailboxes | default([]) }}"

