---
- name: "Set vfs.zfs.arc_max in /boot/loader.conf"
  lineinfile:
    dest: "/boot/loader.conf"
    regexp: "^vfs.zfs.arc_max"
    line: "vfs.zfs.arc_max={{ zfs_arc_max | d(zfs_arc_max_defaults[host_type]) }}"

