---
- name: "Disable HTT (hyperthreading) in /boot/loader.conf"
  lineinfile:
    dest: "/boot/loader.conf"
    regexp: "^machdep.hyperthreading_allowed"
    line: "machdep.hyperthreading_allowed=0"
  tags:
    - "htt"

