---
- include_tasks: "packages.yml"
- include_tasks: "openntpd.yml"
- include_tasks: "smartd.yml"
  when: host_type == "hardware"
- include_tasks: "zfs-periodic.yml"
- include_tasks: "zfs-scrub.yml"
- include_tasks: "aesni.yml"
- include_tasks: "sysctl.yml"
- include_tasks: "arc_max.yml"
- include_tasks: "vmware.yml"
  when: host_type == "vmware"
- include_tasks: "accounting.yml"

