---
- name: "Configure network interfaces (Add /etc/rc.conf.d/netif/* files)"
  template:
    src: "netif.j2"
    dest: "/etc/rc.conf.d/netif/{{ item.name }}"
  with_items: "{{ network_interfaces }}"
  when: item.configure
  tags:
    - "network"
  register: result

- name: "create network interfaces"
  command: "/sbin/ifconfig {{ item.interface }}{% if item.vlan is defined %}.{{ item.vlan }}{% endif %} || /sbin/ifconfig {{ item.interface }}{% if item.vlan is defined %}.{{ item.vlan }}{% endif %} create"
  ignore_errors: yes
  with_items: "{{ network_interfaces }}"
  when: item.configure
  tags:
    - "network"

- name: "(Re-)Configure network interfaces (service netif restart $interface)"
  command: "/usr/sbin/service netif restart {{ item.0.interface }}{% if item.0.vlan is defined %}.{{ item.0.vlan }}{% endif %}"
  with_together:
    - "{{ network_interfaces }}"
    - "{{ result.results }}"
  when:
    - item.0.configure
    - item.1.changed
  tags:
    - "network"
