---
- name: "Install FreeBSD host packages"
  pkgng:
    name: "{{ default_host_packages + extra_host_packages | default([]) }}"
    state: "present"

- name: "Install FreeBSD host_type specific packages"
  pkgng:
    name: "{{ lookup('vars', host_type + '_host_packages', default=[]) }}"
    state: "present"

