---
- name: "Create supervisord.d config file to run ppp if needed"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "ppp"
    supervisord_programs: "{{ ppp_profiles }}"
  when: ppp_profiles is defined
