---
- name: "Install uwsgi"
  pkgng:
    name: "uwsgi"
    state: "present"

- name: "Copy uwsgi config file"
  template:
    src: "uwsgi.ini.j2"
    dest: "/usr/local/etc/uwsgi.ini"
    mode: "0644"
  notify: "restart uwsgi"

- name: "Create uwsgi socket directory"
  file:
    path: "/var/run/uwsgi"
    state: "directory"
    mode: "0755"
    owner: "www"
    group: "www"

- name: "Create prometheus_multiproc_dir"
  file:
    path: "{{ uwsgi_prometheus_multiproc_dir }}"
    state: "directory"
    mode: "0755"
    owner: "www"
    group: "www"

- name: "Install uwsgitop"
  pkgng:
    name: "uwsgitop"
    state: "present"

