---
- name: "Create cron.d file to run poudriere"
  include_role:
    name: "freebsd_base"
    tasks_from: "cron.d"
  vars:
    cron_d_jobs:
      - comment: "Run poudriere.sh daily"
        filename: "poudriere"
        minute: "0"
        hour: "0"
        user: "root"
        command: "/usr/local/bin/poudriere.sh"
