---
- name: "Install poudriere"
  pkgng:
    name: "poudriere"
    state: present

- name: "Copy main poudriere.conf"
  template:
    src: "poudriere.conf.j2"
    dest: "/usr/local/etc/poudriere.conf"

- name: "Copy poudriere portlists"
  template:
    owner: "root"
    group: "wheel"
    mode: "0644"
    src: "portlist.j2"
    dest: "/usr/local/etc/poudriere.d/{{ item['filename'] }}"
  with_items: "{{ poudriere_portlists }}"

- name: "Copy extra poudriere makefiles"
  copy:
    owner: "root"
    group: "wheel"
    mode: "0644"
    content: "{{ item.content }}"
    dest: "/usr/local/etc/poudriere.d/{{ item.filename }}"
  with_items: "{{ poudriere_extra_makefiles | default([]) }}"

- name: "Copy poudriere hook scripts"
  copy:
    owner: "root"
    group: "wheel"
    mode: "0755"
    content: "{{ item.content }}"
    dest: "/usr/local/etc/poudriere.d/hooks/{{ item.filename }}"
  with_items: "{{ poudriere_hook_scripts | default([]) }}"

- name: "Copy poudriere.sh"
  template:
    src: "poudriere.sh.j2"
    dest: "/usr/local/bin/poudriere.sh"
    mode: "0755"

- name: "Create poudriere jails"
  command: "/usr/local/bin/poudriere jail -c -j freebsd_{{ item[0]['versiontag'] }}_{{ item[1] }} -v {{ item[0]['release'] }}"
  args:
    creates: "{{ poudriere_zfs_mountpoint }}/jails/freebsd_{{ item[0]['versiontag'] }}_{{ item[1] }}"
  with_nested:
    - "{{ poudriere_jail_versions }}"
    - "{{ poudriere_jail_architechtures }}"

- name: "Get local patches from git"
  git:
    repo: "{{ poudriere_local_patches_repo }}"
    dest: "/usr/local/etc/poudriere.d/local-patches"
    force: yes
    version: "master"
    accept_hostkey: yes
  when: poudriere_local_patches_repo
