---
- name: "Create supervisord.d config file to run radicale2"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "radicale"
    supervisord_programs:
      - name: "radicale"
        comment: "run radicale"
        command: "/usr/local/bin/python3.7 /usr/local/bin/radicale -C /usr/local/etc/radicale2/config --debug"
        user: "radicale"
        priority: "1"

