---
- name: "Create supervisord.d config file to run etherpad"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "etherpad"
    supervisord_programs:
      - name: "etherpad"
        comment: "run etherpad"
        command: "/usr/local/bin/node {{ etherpadlite_root }}/node_modules/ep_etherpad-lite/node/server.js"
        user: "etherpad"
        directory: "{{ etherpadlite_root }}"
        exitcodes: "255" # so, etherpad exits with exitcode 0 if the database it uses is restarted, so set this to an unlikely exit code, to make supervisord always consider it unexpected whenever etherpad exits without being asked to
        environment:
          NODE_ENV: "production"
          PATH: "/usr/local/bin"
