---
- name: "Create supervisord.d config file to run stund"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "stund"
    supervisord_programs:
      - name: "stund"
        comment: "run stund"
        command: "/usr/local/sbin/stund -h {{ stund_ip1 }} -a {{ stund_ip2 }}"
        user: "nobody"
        priority: "1"

