---
- name: "start nullmailer"
  service:
    name: "nullmailer"
    state: "started"

- name: "restart nullmailer"
  service:
    name: "nullmailer"
    state: "restarted"

- name: "send postfix uninstalled email"
  mail:
    to: "{{ certgrinder_admin_email }}"
    subject: "postfix has been replaced with nullmailer on host {{ ansible_host }}"
    body: "Ansible has uninstalled postfix and installed nullmailer on host {{ ansible_host }}. Please run pkg autoremove on {{ ansible_host }} to clean up dependencies that are no longer needed."

