---
- name: "start nut"
  service:
    name: "nut"
    state: "started"

- name: "restart nut"
  service:
    name: "nut"
    state: "restarted"

- name: "start upsmon"
  service:
    name: "nut_upsmon"
    state: "started"

- name: "restart upsmon"
  service:
    name: "nut_upsmon"
    state: "restarted"
