---
- name: "restart postgresql"
  command: "/usr/local/bin/supervisorctl restart postgresql"

- name: "reload postgresql"
  command: "su -l postgres -c '/usr/local/bin/pg_ctl -D {{ postgresql_datadir }} reload'"

