---
- name: "Install ezjail"
  pkgng:
    name: "ezjail"
    state: "present"

- name: "Copy ezjail config"
  template:
    src: "ezjail.conf.j2"
    dest: "/usr/local/etc/ezjail.conf"

- name: "Bootstrap ezjail (requires a built world in /usr/obj)"
  command: "ezjail-admin update -i"
  args:
    creates: "{{ ezjail_root }}/basejail"
