---
- name: "Create /etc/rc.conf.d/jail directory"
  file:
    path: "/etc/rc.conf.d/jail"
    state: "directory"
    mode: "0755"

- name: "Enable parallel starting of jails"
  sysrc:
    name: "jail_parallel_start"
    value: "YES"

- name: "Create jails filesystems with ezjail"
  command: "/usr/local/bin/ezjail-admin create {{ item.hostname }} 127.0.0.1"
  args:
    creates: "{{ ezjail_root }}/{{ item.hostname }}"
  loop: "{{ jails }}"

- name: "check if main jailstorage zfs exists"
  shell: "/sbin/zfs list {{ ezjail_jailstorage_dataset }}"
  register: ezjail_jailstorage_result
  ignore_errors: True
  changed_when: False

- name: "Create main jailstorage zfs as needed"
  command: "/sbin/zfs create -o mountpoint=none -o jailed=on {{ ezjail_jailstorage_dataset }}"
  when: ezjail_jailstorage_result.rc == 1

- name: "Create jailstorage zfs filesystems as needed"
  shell: "/sbin/zfs list {{ item.1 }} || /sbin/zfs create -o mountpoint=none -o jailed=on {{ item.1 }}"
  loop: "{{ jails | subelements('zfs_datasets', skip_missing=True) }}"

- name: "Template /etc/rc.conf.d/jail/ config files for jails, (re)start if needed."
  template:
    src: "jail.d.j2"
    dest: "/etc/rc.conf.d/jail/{{ jailname }}"
  vars:
    jail: "{{ item }}"
    jailname: "{{ item.hostname|replace('.','_') }}"
  loop: "{{ jails }}"
  notify: "restart changed jails"
  register: jail_results
