---
- name: "Configure jails"
  template:
    src: "jail.d.j2"
    dest: "/etc/rc.conf.d/jail/{{ jailname }}"
  vars:
    jail: "{{ item }}"
    jailname: "{{ item.hostname|replace('.','_') }}"
  loop: "{{ jails }}"
  tags:
    - "jails"
  notify: "restart jail {{ jailname }}"
