---
- name: "Set jail_enable=YES in /etc/rc.conf"
  service:
    name: "jail"
    enabled: yes
  tags:
    - "jail_host"
- include_tasks:
    file: "ezjail.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
- include_tasks:
    file: "flavour.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
- include_tasks:
    file: "jailmergemaster.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
- include_tasks:
    file: "rctl.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
- include_tasks:
    file: "jail_exporter.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
- include_tasks:
    file: "jails.yml"
    apply:
      tags:
        - "jail_host"
        - "jails"
  tags:
    - "jail_host"
    - "jails"
- include_tasks:
    file: "packages.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
- include_tasks:
    file: "jailkeys.yml"
    apply:
      tags:
        - "jail_host"
  tags:
    - "jail_host"
