---
- name: "Install tor"
  pkgng:
    name: "tor"
    state: "present"

- name: "Enable tor"
  service:
    name: "tor"
    enabled: yes

- name: "Enable multiple Tor instances in rc.conf, if there is more than one"
  sysrc:
    name: "tor_instances"
    value: "{% for instance in tor_instances %}{{ instance.name }} {% endfor %}"
  when: tor_instances|length > 1

- name: "Configure Tor instances"
  include_tasks:
    file: "configure_tor_instance.yml"
    apply:
      tags: "torconf"
  vars:
    instance: "{{ item }}"
    datadir: "{% if 'datadir' in item.value %}{{ item.value.datadir }}{% elif item.key == 'main' %}/var/db/tor{% else %}/var/db/tor/instance@{{ item.key }}{% endif %}"
    confpath: "/usr/local/etc/tor/torrc{% if item.key != 'main' %}@{{ item.key }}{% endif %}"
  loop: "{{ tor_instances | dict2items }}"
  tags: "torconf"

- name: "Install socat"
  pkgng:
    name: "socat"
    state: "present"
