---
- name: "Install tor"
  pkgng:
    name: "tor"
    state: "present"

- name: "Enable tor"
  service:
    name: "tor"
    enabled: yes

- name: "Enable multiple Tor instances in rc.conf, if there is more than one"
  sysrc:
    name: "tor_instances"
    value: "{% for instance in tor_instances %}{{ instance.name }} {% endfor %}"
  when: tor_instances|length > 1

- name: "Configure Tor instances"
  include_tasks: "configure_tor_instance"
  vars:
    instance: "{{ item }}"
    datadir: "{% if 'datadir' in item %}{{ item.datadir }}{% elif item.name == 'main' %}/var/db/tor{% else %}/var/db/tor/instance@{{ item.name }}{% endif %}"
    confpath: "/usr/local/etc/tor/torrc{% if item.name != 'main' %}@{{ item.name }}{% endif %}"
  loop: "{{ tor_instances }}"

- name: "Install socat"
  pkgng:
    name: "socat"
    state: "present"
