---
- name: "Install tor"
  pkgng:
    name: "tor"
    state: "present"

- name: "Enable tor"
  service:
    name: "tor"
    enabled: yes

- name: "Configure tor"
  template:
    src: "torrc.j2"
    dest: "/usr/local/etc/tor/torrc"
  notify: "reload tor"
