---
- name: "Install ezjail"
  pkgng:
    name: "ezjail"
    state: "present"

- name: "Enable ezjail"
  service:
    name: "ezjail"
    enabled: yes

- name: "Copy ezjail config"
  template:
    src: "ezjail.conf.j2"
    dest: "/usr/local/etc/ezjail.conf"

- name: "Bootstrap ezjail (requires a built world in /usr/obj)"
  command: "ezjail-admin update -i"
  args:
    creates: "{{ ezjail_root }}/basejail"

- name: "Set syslogd_flags to prevent it listening on all ips"
  sysrc:
    name: "syslogd_flags"
    value: "-s -b 127.0.0.1:514 -b [::1]:514"
  notify: "restart syslogd"

- name: "Set inetd_flags to prevent it listening on all IPs"
  sysrc:
    name: "inetd_flags"
    value: "-wW -C 60 -a 127.0.0.1"
  notify: "restart inetd"

- name: "check if jailstorage zfs exists"
  shell: "/sbin/zfs list {{ ezjail_jailstorage_dataset }}"
  register: ezjail_jailstorage_result
  ignore_errors: True

- name: "Create main jailstorage zfs if neded"
  command: "/sbin/zfs create -o mountpoint=none -o jailed=on {{ ezjail_jailstorage_dataset }}"
  when: ezjail_jailstorage_result.rc == 1

- name: "Patch ezjail to automount zfs datasets after zfs jailing them"
  patch:
    src: "../files/ezjail.zfsautomount.patch"
    dest: "/usr/local/etc/rc.d/ezjail"

