---
- name: "Get source code for jail_exporter with git"
  git:
    repo: "https://github.com/phyber/jail_exporter"
    dest: "/root/jail_exporter"
    force: yes
    version: "{{ jail_exporter_version }}"
  register: gitresult

- name: "Install rust for the build"
  pkgng:
    name: "rust"
    state: "present"
  register: rustresult
  when: gitresult.changed

- name: "Build jail_exporter"
  command: "make release"
  args:
    chdir: "/root/jail_exporter"
  when: gitresult.changed

- name: "Uninstall rust if this role installed it"
  pkgng:
    name: "go"
    state: "absent"
  when:
    - gitresult.changed
    - rustresult

- name: "Copy jail_exporter binary to /usr/local/bin"
  copy:
   src: "/root/jail_exporter/target/release/jail_exporter"
   dest: "/usr/local/bin/jail_exporter"
   mode: "0755"
   remote_src: yes
  when:
    - gitresult.changed
  notify:
    - "restart jail_exporter"

- name: "Create supervisord.d config file to run jail_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "jail_exporter"
    supervisord_programs:
      - name: "jail_exporter"
        comment: "run jail_exporter"
        command: "/usr/local/bin/jail_exporter"
        user: "root"
    supervisord_extra_programs: []

- name: "Enable racct (rctl) in /boot/loader.conf"
  lineinfile:
    dest: "/boot/loader.conf"
    regexp: "^kern.racct.enable="
    line: "kern.racct.enable=1"
    state: "present"

- name: "Create exporter_exporter.d config file for jail_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "jail_exporter.yml"
    expexp_program:
      method: "http"
      http:
        port: 9452
