---
- name: "Create certgrinder post-renew-hooks.d directory"
  file:
    path: "{{ certgrinder_home }}/hooks.d"
    state: "directory"
    mode: "0755"

- name: "Create Certgrinder post-renew-hooks-dir file"
  copy:
    content: "{{ hookfile }}"
    dest: "{{ certgrinder_home }}/hooks.d/{{ hookname }}"
    mode: "755"

- name: "Add sudoers permission so the certgrinder user can run the post renew hook"
  copy:
    content: "{{ certgrinder_user }} ALL=(ALL) NOPASSWD: {{ certgrinder_home }}/hooks.d/{{ hookname }}\n"
    dest: "/usr/local/etc/sudoers.d/certgrinder-hook-{{ hookname }}"
    validate: "visudo -cf %s"
