---
- name: "Enable daily cronjob to run certgrinder"
  cron:
    name: "Run certgrinder daily"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    job: "/usr/local/bin/certgrinder --config-file {{ certgrinder_home }}/certgrinder.conf --quiet --now periodic"
    cron_file: "certgrinder"
    user: "{{ certgrinder_user }}"
