---
- name: "Enable daily cronjob to run certgrinder"
  cron:
    name: "Run certgrinder daily"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    job: "{{ certgrinder_home }}/virtualenv/bin/certgrinder --config-file {{ certgrinder_home }}usr/home/certgrinder.conf --quiet --now periodic"
    cron_file: "/etc/crontab"
    user: "{{ certgrinder_user }}"
