---
- name: "Enable daily cronjob to run certgrinder"
  cron:
    name: "Run certgrinder daily at a random time"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    job: "/usr/home/{{ certgrinder_user }}/virtualenv/bin/certgrinder --config-file /usr/home/{{ certgrinder_user }}/certgrinder.conf --quiet --now periodic"
    cron_file: "/etc/crontab"
    user: "{{ certgrinder_user }}"
