---
- name: "Enable daily cronjob to run certgrinder"
  cron:
    name: "Run certgrinder daily"
    minute: "{{ 59 | random }}"
    hour: "{{ 23 | random }}"
    job: "/usr/home/{{ certgrinder_user }}/virtualenv/bin/python /usr/home/{{ certgrinder_user }}/certgrinder/certgrinder.py -q /usr/home/{{ certgrinder_user }}/certgrinder.yml"
    cron_file: "/etc/crontab"
    user: "certgrinder"

