---
- include_tasks: "syslog.yml"
- include_tasks: "newsyslog.yml"
- include_tasks:
    file: "user.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
- include_tasks:
    file: "certgrinder.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
- include_tasks: "cron.yml"
- include_tasks: "renamelegacy.yml"
  when: certgrinder_rename_legacy
  tags: "renamelegacy"
