---
- include_tasks:
    file: "syslog.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
- include_tasks:
    file: "newsyslog.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
- include_tasks:
    file: "user.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
  when: certgrinder_pip_install
- include_tasks:
    file: "certgrinder.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
  when: certgrinder_pip_install
- include_tasks:
    file: "package.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
  when: not certgrinder_pip_install
- include_tasks:
    file: "cron.yml"
    apply:
      tags:
        - "certgrinder"
  tags:
    - "certgrinder"
- include_tasks: "renamelegacy.yml"
  when: certgrinder_rename_legacy
  tags: "renamelegacy"
