---
- name: "Install certgrinder"
  pkgng:
    name: "py37-certgrinder"
    state: "present"

- name: "Create certgrinder.conf config file"
  template:
    src: "certgrinder.conf.j2"
    dest: "{{ certgrinder_home }}/certgrinder.conf"
    owner: "{{ certgrinder_user }}"
    mode: "0644"
