---
- name: "Install python"
  pkgng:
    name: "python"
    state: "present"

- name: "Install pip"
  pkgng:
    name: "py37-pip"
    state: "present"

- name: "Install setuptools"
  pkgng:
    name: "py37-setuptools"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py37-virtualenv"
    state: "present"

- name: "Create new virtualenv and install cryptography. Use CFLAGS and LDFLAGS env vars to force pip to use /usr/local/ ports OpenSSL libs+include"
  pip:
    virtualenv_python: "python"
    name: "cryptography"
    virtualenv: "/usr/home/{{ certgrinder_user }}/virtualenv"
    extra_args: '--global-option=build_ext'
  environment:
    CFLAGS: "-I/usr/local/include"
    LDFLAGS: "-L/usr/local/include"

- name: "Upgrade pip to latest version to avoid problems when installing cffi"
  pip:
    name: "pip"
    state: "latest"
    virtualenv: "/usr/home/{{ certgrinder_user }}/virtualenv"

- name: "Install the rest of requirements.txt modules with pip"
  pip:
    requirements: "/usr/home/{{ certgrinder_user }}/certgrinder/requirements.txt"
    virtualenv: "/usr/home/{{ certgrinder_user }}/virtualenv"

