---

# .key files

- name: "Check if we have .key files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}.key"
  register: old_key_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any .key files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.key"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-keypair.rsa.key"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0640"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_key_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old .key file with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.key"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_key_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

# CSR files

- name: "Check if we have .csr files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}.csr"
  register: old_csr_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any .csr files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.csr"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-request.rsa.csr"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0644"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_csr_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old .csr file with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.csr"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_csr_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

# certificate chain files

- name: "Check if we have certificate chain .crt files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}.crt"
  register: old_crt_chain_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any certificate chain .crt files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.crt"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-chain.rsa.crt"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0644"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_crt_chain_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old certificate chain .crt file with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.crt"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_crt_chain_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

# certificate (only) files

- name: "Check if we have certonly .crt files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}-certonly.crt"
  register: old_crt_only_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any certonly .crt files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}-certonly.crt"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-certificate.rsa.crt"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0644"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_crt_only_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old certonly .crt files with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}-certonly.crt"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_crt_only_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

# key + cert concat files

- name: "Check if we have concat .pem files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}-concat.pem"
  register: old_concat_pem_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any concat .pem files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}-concat.pem"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-concat.rsa.pem"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0640"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_concat_pem_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old concat .pem files with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}-concat.pem"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_concat_pem_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

# issuer certificate files

- name: "Check if we have issuer .crt files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}-issuer.crt"
  register: old_issuer_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any issuer .crt files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}-issuer.crt"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-issuer.rsa.crt"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0644"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_issuer_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old issuer .crt files with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}-issuer.crt"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_issuer_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

# OCSP response files

- name: "Check if we have ocsp response files with pre-0.15 filenames which need renaming"
  stat:
    path: "{{ certgrinder_home }}/certificates/{{ item.split(',')[0].encode('idna').decode('ascii') }}.ocsp"
  register: old_ocsp_files_results
  changed_when: False
  with_items: "{{ certgrinder_hostname_sets }}"
  tags: "renamelegacy"

- name: "Copy any ocsp response files with pre-0.15 filenames to new filename"
  copy:
    src: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.ocsp"
    dest: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii')[-230:] }}-response.rsa.ocsp"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    mode: "0644"
    remote_src: True
  loop: "{{ certgrinder_hostname_sets|zip(old_ocsp_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"

- name: "Remove the old ocsp response files with pre-0.15 filename"
  file:
    path: "{{ certgrinder_home }}/certificates/{{ item.0.split(',')[0].encode('idna').decode('ascii') }}.ocsp"
    state: "absent"
  loop: "{{ certgrinder_hostname_sets|zip(old_ocsp_files_results.results)|list }}"
  when: item.1.stat.exists
  tags: "renamelegacy"
