---
- name: "Install dnsdist"
  pkgng:
    name: "dnsdist"
    state: "present"

- name: "Copy dnsdist.conf"
  template:
    src: "dnsdist.conf.j2"
    dest: "/usr/local/etc/dnsdist.conf"
  notify: "restart dnsdist"

