---
- name: "Install dnsdist"
  pkgng:
    name: "dnsdist"
    state: "present"

- name: "Copy dnsdist.conf"
  template:
    src: "dnsdist.conf.j2"
    dest: "/usr/local/etc/dnsdist/dnsdist.conf"
    mode: "600"
  tags: "dnsdistconf"
  notify: "restart dnsdist"

- name: "Create exporter_exporter.d config file for dnsdist"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "dnsdist.yml"
    expexp_program:
      method: "http"
      http:
        address: "{{ dnsdist_web_mgmt_v6_listen_ip }}"
        port: "{{ dnsdist_web_mgmt_v6_listen_port }}"
        basic_auth_username: "dnsdist"
        basic_auth_password: "{{ dnsdist_web_password }}"
