---
- name: "Create supervisord.d config file to run dnsdist"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "dnsdist"
    supervisord_programs:
      - name: "dnsdist"
        comment: "run dnsdist"
        command: "/usr/local/sbin/dnsdist"
        user: "root"

