---
- name: "Enable ctld"
  service:
    name: "ctld"
    enabled: yes

- name: "Copy ctld config"
  template:
    src: "ctld.conf.j2"
    dest: "/etc/ctld.conf"

- name: "Start ctld (if not running)"
  service:
    name: "ctld"
    state: "started"

