---
- name: "add syslog.d config for nfsen"
  template:
    src: "nfsen_syslogd.conf.j2"
    dest: "/usr/local/etc/syslog.d/nfsen.conf"
  notify:
    - "restart syslogd"

- name: "Make sure nfsen logfile exists"
  copy:
    dest: "{{ nfsen_logfile_path }}"
    content: ""
    force: "no"
  notify:
    - "restart syslogd"

- name: "Make sure nfsen newsyslog config file exists"
  template:
    src: "nfsen_newsyslog.conf.j2"
    dest: "/usr/local/etc/newsyslog.conf.d/nfsen.conf"

