---
- name: "Install ansible"
  pkgng:
    name: "py37-ansible"
    state: "present"

- name: "Install ansible config deploy.sh script"
  template:
    src: "deploy.sh.j2"
    dest: "/root/deploy.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"

- name: "Create symlink from /usr/local/etc/py37-ansible/ to /usr/local/etc/ansible/"
  file:
    src: "/usr/local/etc/ansible"
    dest: "/usr/local/etc/py37-ansible"
    state: "link"

