---
- name: "Enable nightly cronjob to check various things"
  cron:
    name: "ansible check_stuff.sh"
    hour: "4"
    minute: "30"
    job: "/usr/local/etc/ansible/roles/library/check_stuff.sh {{ ansible_admin_email }}"
    cron_file: "ansible_check_stuff"
    user: "ansible"

