---
- name: "Get sshfp code from git"
  git:
    repo: "https://github.com/tykling/check_sshfp"
    dest: "/usr/home/{{ ansible_user }}/check_sshfp"
    force: yes
    version: "master"
    accept_hostkey: yes

- name: "Install py37-dnspython"
  pkgng:
    name: "py37-dnspython"
    state: "present"

