---
- name: "Create supervisord.d program config files"
  template:
    src: "supervisord.d.conf.j2"
    dest: "/usr/local/etc/supervisord.d/{{ item.name }}.conf"
  vars:
    type: "program"
  notify:
    - "reread supervisord config"
    - "update supervisord config"
  loop: "{{ supervisord_programs | default([]) | flatten(levels=1) }} + {{ supervisord_extra_programs | default([]) | flatten(levels=1) }}"

- name: "Create supervisord.d fcgi-program config files"
  template:
    src: "supervisord.d.conf.j2"
    dest: "/usr/local/etc/supervisord.d/{{ item.name }}.conf"
  vars:
    type: "fcgi-program"
  notify:
    - "reread supervisord config"
    - "update supervisord config"
  loop: "{{ supervisord_fcgi_programs | default([]) | flatten(levels=1) }} + {{ supervisord_extra_fcgi_programs | default([]) | flatten(levels=1) }}"

