---
- name: "add syslog.d config for supervisord"
  template:
    src: "supervisord_syslogd.conf.j2"
    dest: "/usr/local/etc/syslog.d/supervisord.conf"
    owner: "root"
    group: "wheel"
    mode: "755"
  notify:
    - "restart syslogd"

- name: "Make sure /var/log/supervisord.log exists"
  copy:
    content: ""
    dest: "{{ supervisord_logfile }}"
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

- name: "Make sure supervisord newsyslog config file exists"
  template:
    src: "supervisord_newsyslog.conf.j2"
    dest: "/usr/local/etc/newsyslog.conf.d/supervisord.conf"
    owner: "root"
    group: "wheel"
    mode: "755"

