---
- name: "Install certgrinderd"
  pkgng:
    name: "py{{ python_nodotversion }}-certgrinderd"
    state: "present"

- name: "Create certgrinderd.conf config file"
  template:
    src: "certgrinderd.conf.j2"
    dest: "{{ certgrinderd_home }}/certgrinderd.conf"
    owner: "{{ certgrinderd_user }}"
    mode: "0644"

- name: "Make sure PermitUserEnvironment=CERTGRINDERD_DOMAINSETS is set in sshd_config"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitUserEnvironment="
    line: "PermitUserEnvironment=CERTGRINDERD_DOMAINSETS"
    state: "present"
  notify:
    - "restart sshd"
