---
- name: "add syslog.d config for certgrinderd"
  copy:
    src: "certgrinderd-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/certgrinderd.conf"
  notify: "restart syslogd"

- name: "Make sure /var/log/certgrinderd.log exists"
  copy:
    dest: "/var/log/certgrinderd.log"
    content: ""
    force: False
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"
