---
- name: "Add /usr/local/etc/sudoers.d config for certgrinderd"
  template:
    src: "sudoers.d.j2"
    dest: "/usr/local/etc/sudoers.d/certgrinderd"

- name: "Remove existing SSH authorized_keys file"
  file:
    path: "{{ certgrinderd_home }}/.ssh/authorized_keys"
    state: "absent"
  tags: "sshkeys"

- name: "Add ssh authorized_keys for all certgrinder clients"
  authorized_key:
    user: "{{ certgrinderd_user }}"
    key: "{{ item.value.authkey }}"
    key_options: 'from="{% if item.value.fromip is string %}{{ item.value.fromip }}{% else %}{{ item.value.fromip|join(",") }}{% endif %}",environment="CERTGRINDERD_DOMAINSETS={% for ds in item.value.domainsets %}{% if ds is string %}{{ ds }}{% else %}{{ ds|join(",") }}{% endif %};{% endfor %}",command="~/virtualenv/bin/certgrinderd $SSH_ORIGINAL_COMMAND",restrict'
  loop: "{{ certgrinderd_authorized_keys | default({}) | dict2items }}"
  tags: "sshkeys"

