---
- name: "Add /usr/local/etc/sudoers.d config for certgrinderd"
  template:
    src: "sudoers.d.j2"
    dest: "/usr/local/etc/sudoers.d/certgrinderd"

- name: "Add ssh authorized_keys for all certgrinder clients"
  template:
    src: "authorized_keys.j2"
    dest: "{{ certgrinderd_home }}/.ssh/authorized_keys"
    owner: "{{ certgrinderd_user }}"
    group: "{{ certgrinderd_user }}"
    mode: "0600"
  tags: "sshkeys"
