---
- include_tasks: "postgresql.yml"
  tags:
    - "pghba"
- include_tasks: "ip4r.yml"
- include_tasks: "syslog.yml"
- include_tasks: "newsyslog.yml"
- include_tasks: "supervisord.yml"
- include_tasks: "periodic-daily.yml"
- include_tasks: "pgbouncer.yml"
  when: postgresql_pgbouncer
- include_tasks: "replicabackup.yml"
- include_tasks: "partitioning.yml"
  when: postgresql_partitioning_databases is defined

