---
- include_tasks:
    file: "postgresql.yml"
    apply:
      tags:
        - "postgresql"
        - "pghba"
  tags:
    - "postgresql"
    - "pghba"
- include_tasks:
    file: "ip4r.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
- include_tasks:
    file: "syslog.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
- include_tasks:
    file: "newsyslog.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
- include_tasks:
    file: "supervisord.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
- include_tasks:
    file: "periodic-daily.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
- include_tasks:
    file: "pgbouncer.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
  when: postgresql_pgbouncer
- include_tasks:
    file: "replicabackup.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
- include_tasks:
    file: "partitioning.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
  when: postgresql_partitioning_databases|default(False)
- include_tasks:
    file: "postgres_exporter.yml"
    apply:
      tags:
        - "postgresql"
  tags:
    - "postgresql"
