---
- name: "Make sure postgresql newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "postgresql-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/postgresql.conf"

- name: "Make sure pgbouncer newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "pgbouncer-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/pgbouncer.conf"

