---
- name: "Enable daily postgres vacuum in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_vacuum_enable"
    value: "YES"
    dest: "/etc/periodic.conf"
  when: postgresql_daily_vacuum_enable

- name: "Enable daily postgres backup in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_backup_enable"
    value: "YES"
    dest: "/etc/periodic.conf"
  when: postgresql_daily_backup_enable

- name: "Set destination dir for postgres backups in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_backupdir"
    value: "{{ postgresql_backup_path }}"
    dest: "/etc/periodic.conf"

- name: "Make sure backup destination is writable"
  file:
    path: "{{ postgresql_backup_path }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0700"

- name: "Set savedays for postgres backups in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_savedays"
    value: "{{ postgresql_backup_savedays }}"
    dest: "/etc/periodic.conf"

- name: "Set daily_pgsql_user /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_user"
    value: "{{ postgresql_user }}"
    dest: "/etc/periodic.conf"

# this does not work
#- name: "Make sure postgres backupdir is a mountpoint"
#  fail:
#    msg: "The postgresql backupdir {{ postgresql_backup_path }} is not a mountpoint"
#  when: postgresql_check_mounts and postgresql_backup_path is not mount

