---
- name: "Install PostgreSQL"
  pkgng:
    name: "postgresql{{ postgresql_version }}-server"
    state: "present"

- name: "Install PostgreSQL contrib"
  pkgng:
    name: "postgresql{{ postgresql_version }}-contrib"
    state: "present"

- name: "Install Postgis"
  pkgng:
    name: "{{ postgis_package }}"
    state: "present"
  when: postgresql_postgis

- name: "Make sure postgres homedir is owned by postgres:postgres"
  file:
    dest: "{{ postgresql_homedir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    state: "directory"
  notify: "reload postgresql"

# this does not work
#- name: "Make sure postgres homedir is a mountpoint"
#  fail:
#    msg: "The postgresql homedir {{ postgresql_homedir }} is not a mountpoint"
#  when: postgresql_check_mounts and postgresql_homedir is not mount

- name: "Initialise PostgreSQL database"
  command: "/usr/sbin/service postgresql oneinitdb"
  args:
    creates: "{{ postgresql_datadir }}"
  notify: "reload postgresql"

- name: "Copy config file"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0600"
  notify: "restart postgresql"

- name: "Copy pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_datadir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0600"
  tags:
    - "pghba"
  notify: "reload postgresql"

- name: "Create certgrinder hooks.d file to copy certs and reload postgresql"
  include_role:
    name: "certgrinder_client"
    tasks_from: "certgrinder_hook.d"
  vars:
    hookname: "postgresql"
    hookfile: |
      #!/bin/sh
      /bin/cp {{ certgrinder_home }}/certificates/{{ ansible_nodename }}-chain.rsa.crt {{ postgresql_homedir }}
      /bin/cp {{ certgrinder_home }}/certificates/{{ ansible_nodename }}-keypair.rsa.key {{ postgresql_homedir }}
      /usr/sbin/chown root {{ postgresql_homedir }}/{{ ansible_nodename }}-*
      /bin/chmod 640 {{ postgresql_homedir }}/{{ ansible_nodename }}-*
      /usr/sbin/service postgresql onereload
