---
- name: "Create supervisord.d config file to run postgres"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "postgresql"
    supervisord_programs:
      - name: "postgresql"
        comment: "run postgresql"
        command: "/usr/local/bin/postgres -D {{ postgresql_datadir }}"
        user: "{{ postgresql_user }}"
        startretries: 200
        stopwaitsecs: 60
        stopsignal: "INT"
        directory: "{{ postgresql_homedir }}"

- name: "Create supervisord.d config file to run pgbouncer"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "pgbouncer"
    supervisord_programs:
      - name: "pgbouncer"
        comment: "run pgbouncer"
        command: "/usr/local/bin/pgbouncer /usr/local/etc/pgbouncer.ini"
        user: "pgbouncer"
  when: postgresql_pgbouncer

