---
- name: "Install syslog-ng"
  pkgng:
    name: "syslog-ng"
    state: "present"

- name: "Copy syslog-ng.conf"
  template:
    src: "syslog-ng.conf.j2"
    dest: "/usr/local/etc/syslog-ng.conf"
  notify: "reload syslog-ng"

- name: "enable syslog-ng"
  service:
    name: "syslog-ng"
    enabled: yes

- name: "set syslog-ng pidfile path in /etc/rc.conf"
  sysrc:
    name: "syslog_ng_pid"
    value: "/var/run/syslog-ng.pid"
  notify: "reload syslog-ng"

- name: "Create certgrinder hooks.d file to reload syslog-ng"
  include_role:
    name: "certgrinder_client"
    tasks_from: "certgrinder_hook.d"
  vars:
    hookname: "syslog-ng"
    hookfile: |
      #!/bin/sh
      /usr/sbin/service syslog-ng reload
