---
- name: "Install powerdns_recursor"
  pkgng:
    name: "powerdns-recursor"
    state: "present"

- name: "Copy recursor.conf"
  template:
    src: "recursor.conf.j2"
    dest: "/usr/local/etc/pdns/recursor.conf"
  notify: "restart powerdns-recursor"

