---
- name: "add syslog.d config for powerdns-recursor"
  template:
    src: "powerdns_recursor_syslogd.conf.j2"
    dest: "/usr/local/etc/syslog.d/powerdns_recursor.conf"
  notify:
    - "restart syslogd"

- name: "Make sure powerdns-recursor logfile exists"
  copy:
    dest: "{{ powerdns_recursor_logfile_path }}"
    content: ""
    force: "no"
  notify:
    - "restart syslogd"

- name: "Make sure powerdns-recursor newsyslog config file exists"
  template:
    src: "powerdns_recursor_newsyslog.conf.j2"
    dest: "/usr/local/etc/newsyslog.conf.d/powerdns_recursor.conf"

