---
- name: "Put any custom extra files into place"
  copy:
    owner: "www"
    group: "www"
    mode: "0640"
    content: "{{ item.content }}"
    dest: "{{ django_root }}/{{ django_mainapp }}/{{ item.filename }}"
  with_items: "{{ django_extra_files | default([]) }}"
  loop_control:
    label: "{{ item.filename }}"
  tags:
    - codedeploy

