---
- include_tasks:
    file: "code.yml"
    apply:
      tags:
        - "django"
        - "codedeploy"
  tags:
    - "django"
    - "codedeploy"
- include_tasks:
    file: "redis.yml"
    apply:
      tags:
        - "django"
  tags:
    - "django"
  when: "django_channels_layer_redis"
- include_tasks:
    file: "pip-packages.yml"
    apply:
      tags:
        - "django"
        - "pip"
  tags:
    - "django"
    - "pip"
- include_tasks:
    file: "django-configuration.yml"
    apply:
      tags:
        - "django"
        - "codedeploy"
  tags:
    - "django"
    - "codedeploy"
- include_tasks:
    file: "custom.yml"
    apply:
      tags:
        - "django"
  tags:
    - "django"
- include_tasks:
    file: "extra-files.yml"
    apply:
      tags:
        - "django"
        - "codedeploy"
  tags:
    - "django"
    - "codedeploy"
- include_tasks:
    file: "cron.d.yml"
    apply:
      tags:
        - "django"
  tags:
    - "django"
- include_tasks:
    file: "supervisord.yml"
    apply:
      tags:
        - "django"
  tags:
    - "django"
