---
- include_tasks: "code.yml"
  tags: "codedeploy"
- include_tasks: "redis.yml"
  when: "django_channels_layer_redis"
- include_tasks: "pip-packages.yml"
  tags:
    - "pip"
- include_tasks: "django-configuration.yml"
  tags:
    - "codedeploy"
    - "djangosettings"
- include_tasks: "extra-files.yml"
  tags:
    - "codedeploy"
- include_tasks: "cron.d.yml"
- include_tasks: "supervisord.yml"

