---
- name: "Install pip"
  pkgng:
    name: "py27-pip"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py27-virtualenv"
    state: "present"

- name: "Install python 3.5 for django virtualenv"
  pkgng:
    name: "python35"
    state: "present"

- name: "Install OS dependencies for django"
  pkgng:
    name: "{{ django_os_dependencies + django_extra_os_dependencies | default([]) }}"
    state: "present"

- name: "Install gettext-tools if neded"
  pkgng:
    name: "gettext-tools"
    state: "present"
  when: django_i18n | default(False)

- name: "Install needed pip modules"
  pip:
    requirements: "{{ django_pip_requirements_path }}"
    virtualenv: "{{ django_virtualenv_path }}"
    virtualenv_python: "{{ django_python_path }}"
  environment:
    LANG: "C.UTF-8"
  tags:
    - "pip"

- name: "Install uwsgi in virtualenv"
  pip:
    name: "uwsgi"
    virtualenv: "{{ django_virtualenv_path }}"
    virtualenv_python: "{{ django_python_path }}"

- name: "Install redis for django channel_layer where needed"
  pkgng:
    name: "databases/redis"
    state: "present"
  when: django_channels_layer_redis

- name: "Install channels_redis pip package for django channel_layer where needed"
  pip:
    name: "channels_redis"
    virtualenv: "{{ django_virtualenv_path }}"
    virtualenv_python: "{{ django_python_path }}"
  when: django_channels_layer_redis

