---
- name: "Create supervisord.d config file to run atheme-services"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "atheme-services"
    supervisord_programs:
      - name: "atheme_services"
        comment: "run atheme-services"
        command: "/usr/local/bin/atheme-services -n -c /usr/local/etc/atheme/atheme.conf -l /var/log/atheme/atheme.log -D /var/lib/atheme"
        user: "ircservices"

