---
- name: "Make sure grafana newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "grafana-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/grafana.conf"

