---
- name: "Make sure grafana provisioning config directory exists"
  file:
    path: "{{ grafana_provisioning_config_path }}"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"
  notify:
    - "restart grafana"

- name: "Make sure grafana provisioning config sub-directories exist"
  file:
    path: "{{ grafana_provisioning_config_path }}/{{ item }}"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"
  loop:
    - "dashboards"
    - "datasources"
    - "plugins"
    - "notifiers"
  notify:
    - "restart grafana"

- name: "Install Grafana dashboard provisioning config"
  template:
    src: "dashboards.yml.j2"
    dest: "{{ grafana_provisioning_config_path }}/dashboards/ansible-dashboards.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  notify:
    - "restart grafana"

- name: "Copy grafana dashboards"
  copy:
    src: "dashboards/"
    dest: "{{ grafana_provisioning_dashboard_path }}"
  notify:
    - "restart grafana"

- name: "Copy grafana datasources"
  copy:
    src: "dashboards/"
    dest: "{{ grafana_provisioning_datasource_path }}"
  notify:
    - "restart grafana"

- name: "Copy grafana plugins"
  copy:
    src: "dashboards/"
    dest: "{{ grafana_provisioning_plugin_path }}"
  notify:
    - "restart grafana"

- name: "Copy grafana notifiers"
  copy:
    src: "dashboards/"
    dest: "{{ grafana_provisioning_notifier_path }}"
  notify:
    - "restart grafana"
