---
- name: "Make sure grafana provisioning directory exists"
  file:
    path: "{{ grafana_provisioning_config_path }}"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"

- name: "Make sure grafana dashboard provisioning directory exists"
  file:
    path: "{{ grafana_provisioning_config_path }}/dashboards"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"

- name: "Install Grafana dashboard provisioning config"
  template:
    src: "dashboards.yml.j2"
    dest: "{{ grafana_provisioning_config_path }}/dashboards/ansible-dashboards.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  notify:
    - "restart grafana"

- name: "Copy grafana dashboard templates"
  copy:
    src: "dashboards/"
    dest: "{{ grafana_provisioning_dashboard_path }}"

- name: "Install alertmanager datasource using grafana-cli"
  command: "grafana-cli plugins install camptocamp-prometheus-alertmanager-datasource"
  args:
    creates: "/var/db/grafana/plugins/camptocamp-prometheus-alertmanager-datasource"
