---
- include_tasks:
    file: "postfix.yml"
    apply:
      tags:
        - "postfix"
  tags:
    - "postfix"
- include_tasks:
    file: "opendkim.yml"
    apply:
      tags:
        - "postfix"
  tags:
    - "postfix"
- include_tasks:
    file: "mailecho.yml"
    apply:
      tags:
        - "postfix"
  tags:
    - "postfix"
- include_tasks:
    file: "mailman.yml"
    apply:
      tags:
        - "postfix"
  tags:
    - "postfix"
  when: mailman
- include_tasks:
    file: "thttpd.yml"
    apply:
      tags:
        - "postfix"
  tags:
    - "postfix"
  when: mailman
