---
- name: "Install postfix"
  pkgng:
    name: "postfix"
    state: "present"

- name: "Enable postfix"
  service:
    name: "postfix"
    enabled: yes

- name: "Disable sendmail stuff in /etc/periodic.conf"
  blockinfile:
    create: yes
    dest: "/etc/periodic.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK disable sendmail tasks"
    content: |
      daily_clean_hoststat_enable="NO"
      daily_status_mail_rejects_enable="NO"
      daily_status_include_submit_mailq="NO"
      daily_submit_queuerun="NO"

- name: "Copy postfix main.cf"
  template:
    src: "main.cf.j2"
    dest: "/usr/local/etc/postfix/main.cf"
  notify: "reload postfix"

- name: "Copy postfix smtpd_sender_login_maps.sql"
  template:
    src: "smtpd_sender_login_maps.sql.j2"
    dest: "/usr/local/etc/postfix/smtpd_sender_login_maps.sql"
    mode: "600"
  notify: "reload postfix"

- name: "Copy postfix access.sql"
  template:
    src: "access.sql.j2"
    dest: "/usr/local/etc/postfix/access.sql"
    mode: "600"
  notify: "reload postfix"

- name: "Copy postfix transport.sql"
  template:
    src: "transport.sql.j2"
    dest: "/usr/local/etc/postfix/transport.sql"
    mode: "600"
  notify: "reload postfix"

- name: "Copy postfix virtual_alias_maps.sql"
  template:
    src: "virtual_alias_maps.sql.j2"
    dest: "/usr/local/etc/postfix/virtual_alias_maps.sql"
    mode: "600"
  notify: "reload postfix"

- name: "Copy postfix virtual_mailbox_maps.sql"
  template:
    src: "virtual_mailbox_maps.sql.j2"
    dest: "/usr/local/etc/postfix/virtual_mailbox_maps.sql"
    mode: "600"
  notify: "reload postfix"

- name: "Copy postfix virtual_mailbox_domains.sql"
  template:
    src: "virtual_mailbox_domains.sql.j2"
    dest: "/usr/local/etc/postfix/virtual_mailbox_domains.sql"
    mode: "600"
  notify: "reload postfix"

- name: "Copy postfix virtual_alias_domains.sql file"
  template:
    mode: "600"
    src: "virtual_alias_domains.sql.j2"
    dest: "/usr/local/etc/postfix/virtual_alias_domains.sql"
  notify: "reload postfix"

- name: "Run postalias"
  shell: "/usr/local/sbin/postalias /etc/aliases"

- name: "Copy postfix transport file"
  template:
    mode: "644"
    src: "transport.j2"
    dest: "/usr/local/etc/postfix/transport"
  notify: "reload postfix"

- name: "Enable submission (587) in master.cf"
  blockinfile:
    create: yes
    dest: "/usr/local/etc/postfix/master.cf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK submission"
    content: |
      submission inet n       -       n       -       -       smtpd
        -o cleanup_service_name=$privacy_cleanup_service_name
        -o syslog_name=postfix/submission
        -o smtpd_tls_security_level=encrypt
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_reject_unlisted_recipient=no
        -o smtpd_client_restrictions=
        -o smtpd_helo_restrictions=
        -o smtpd_sender_restrictions=
        -o smtpd_recipient_restrictions=
        -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
        -o milter_macro_daemon_name=ORIGINATING
  notify: "reload postfix"

- name: "Enable smtps (465) in master.cf"
  blockinfile:
    create: yes
    dest: "/usr/local/etc/postfix/master.cf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK smtps"
    content: |
      smtps     inet  n       -       n       -       -       smtpd
        -o cleanup_service_name=$privacy_cleanup_service_name
        -o syslog_name=postfix/smtps
        -o smtpd_tls_wrappermode=yes
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_reject_unlisted_recipient=no
        -o smtpd_client_restrictions=
        -o smtpd_helo_restrictions=
        -o smtpd_sender_restrictions=
        -o smtpd_recipient_restrictions=
        -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
        -o milter_macro_daemon_name=ORIGINATING
  notify: "reload postfix"

- name: "Enable privacy_cleanup service in master.cf"
  blockinfile:
    create: yes
    dest: "/usr/local/etc/postfix/master.cf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK privacy_cleanup"
    content: |
      privacy_cleanup   unix  n       -       n       -       0       cleanup
        -o header_checks=$privacy_header_checks
  notify: "reload postfix"

- name: "Change so we keep a years maillogs in newsyslog.conf"
  lineinfile:
    dest: "/etc/newsyslog.conf"
    regexp: "^/var/log/maillog"
    line: "/var/log/maillog                        640  365   *    @T00  JC"

- name: "Write privacy_header_checks.regexp file"
  copy:
    dest: "/usr/local/etc/postfix/privacy_header_checks.regexp"
    mode: "0640"
    owner: "root"
    group: "wheel"
    content: |
      # Remove Received: header showing clients ip for authenticated locally submitted email
      /^Received:.* with ESMTPSA id/ IGNORE

      # Remove X-Originating-IP
      /^X-Originating-IP:/ IGNORE

      # Remove X-Mailer and User-Agent
      /^X-Mailer:/ IGNORE
      /^User-Agent:/ IGNORE

- name: "enable Postfix in mailer.conf"
  copy:
    dest: "/usr/local/etc/mail/mailer.conf"
    mode: "0640"
    owner: "root"
    group: "wheel"
    content: |
      # Execute the Postfix sendmail program, named /usr/local/sbin/sendmail
      sendmail        /usr/local/sbin/sendmail
      send-mail       /usr/local/sbin/sendmail
      mailq           /usr/local/sbin/sendmail
      newaliases      /usr/local/sbin/sendmail

- name: "Run certgrinder"
  command: "/usr/bin/su {{ certgrinder_user }} -c '/usr/local/bin/certgrinder --config-file {{ certgrinder_home }}/certgrinder.conf --now periodic'"
