---
- name: "Create supervisord.d config file to run openbgpd"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "openbgpd"
    supervisord_programs:
      - name: "openbgpd"
        comment: "run openbgpd"
        command: "/usr/bin/limits -C daemon /usr/local/sbin/bgpd -d"
        user: "0"
        autostart: "{{ openbgpd_autostart }}"

