---
- name: "add syslog.d config for openbgpd"
  copy:
    src: "openbgpd-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/openbgpd.conf"
  notify:
    - "restart syslogd"

- name: "Make sure /var/log/openbgpd.log exists"
  copy:
    dest: "/var/log/openbgpd.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

