---
- include_tasks:
    file: "motion.yml"
    apply:
      tags:
        - "motion"
  tags:
    - "motion"
- include_tasks:
    file: "supervisord.yml"
    apply:
      tags:
        - "motion"
  tags:
    - "motion"
