---
- name: "Copy the prometheus bind_exporter binary into place"
  copy:
    owner: "root"
    group: "wheel"
    mode: "0755"
    src: "bind_exporter"
    dest: "/usr/local/bin/bind_exporter"

- name: "Create supervisord.d config file to run bind_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "bind_exporter"
    supervisord_programs:
      - name: "bind_exporter"
        comment: "run prometheus bind_exporter"
        command: "/usr/local/bin/bind_exporter -bind.stats-url {{  bind_statsurl }} -bind.stats-groups 'server,view,tasks' -log.format logger:syslog?appname=prometheusbind&local=5"
        user: "0"
    supervisord_extra_programs: []

