---
- name: "Make sure freebsd_sysctl_exporter is enabled in inetd.conf"
  lineinfile:
    dest: "/etc/inetd.conf"
    regexp: "prom-sysctl	stream	tcp	nowait	nobody	/usr/sbin/prometheus_sysctl_exporter	prometheus_sysctl_exporter -dgh"
    line: "prom-sysctl	stream	tcp	nowait	nobody	/usr/sbin/prometheus_sysctl_exporter	prometheus_sysctl_exporter -dgh"
  notify:
    - "reload inetd"

- name: "Enable nginx"
  service:
    name: "nginx"
    enabled: yes
  notify:
    - "restart inetd"

