---
- include_tasks: "user.yml"
- include_tasks: "exporter_exporter.yml"
- include_tasks: "freebsd_sysctl_exporter.yml"
  when: "'freebsd_hosts' in group_names"
- include_tasks: "node_exporter.yml"
- include_tasks: "node_exporter_textfile_collector_pkg.yml"
- include_tasks: "node_exporter_textfile_collector_smartmon.yml"
  when: "'freebsd_hosts' in group_names"
- include_tasks: "postgres_exporter.yml"
  when: "'postgresql_servers' in group_names"
- include_tasks: "uwsgi_exporter.yml"
  when: ('uwsgi_servers' in group_names) or ('django_channels2_servers' in group_names)
- include_tasks: "gstat_exporter.yml"
  when: "'freebsd_hosts' in group_names"
- include_tasks: "jail_exporter.yml"
  when: "'ezjail_hosts' in group_names"
- include_tasks: "bind_exporter.yml"
  when: ('bind_servers' in group_names) or ('certgrinder_servers' in group_names)

