---
- name: "Install Go"
  pkgng:
    name: "go"
    state: "present"

- name: "Get source code for postgres_exporter with git so we know when it changed, not used for the build"
  git:
    repo: "https://github.com/wrouesnel/postgres_exporter"
    dest: "/root/postgres_exporter"
    force: yes
    version: "{{ postgres_exporter_version }}"
  register: gitresult

- name: "Go get postgres_exporter (download source and deps)"
  command: "go get github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter"
  environment:
    GOPATH: "/root/go"
    GOBIN: "/usr/local/bin"
  when: gitresult.changed

- name: "Build postgres_exporter with Mage"
  command: "go run mage.go binary"
  args:
    chdir: "/root/go/src/github.com/wrouesnel/postgres_exporter"
  when: gitresult.changed

- name: "Find postgres_exporter binary"
  find:
    paths: "/root/go/src/github.com/wrouesnel/postgres_exporter/bin/"
    recurse: yes
    patterns: "postgres_exporter"
  register: findresult
  when: gitresult.changed

- name: "Copy postgres_exporter binary to /usr/local/bin"
  copy:
   src: "{{ findresult['files'][0].path }}"
   dest: "/usr/local/bin/postgres_exporter"
   remote_src: yes
  when:
    - gitresult.changed
  notify:
    - "restart postgres_exporter"

- name: "Create supervisord.d config file to run postgres_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "postgres_exporter"
    supervisord_programs:
      - name: "postgres_exporter"
        comment: "run postgres_exporter"
        command: "/usr/local/bin/postgres_exporter --auto-discover-databases"
        user: "{{ postgresql_user }}"
        environment:
          DATA_SOURCE_NAME: "host={{ ansible_nodename }}"
  notify:
    - "restart postgres_exporter"

