---
- name: "Install Go"
  pkgng:
    name: "go"
    state: "present"

- name: "Go get postgres_exporter (download source and deps)"
  command: "go get github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter"
  args:
    chdir: "/tmp/postgres_exporter"
  environment:
    GOPATH: "/root/go"
    GOBIN: "/usr/local/bin"
  when: gitresult.changed

- name: "Build postgres_exporter with Mage"
  command: "go run mage.go binary"
  args:
    chdir: "/root/go/src/github.com/wrouesnel/postgres_exporter"
  when: gitresult.changed

- name: "Find postgres_exporter binary"
  find:
    paths: "/root/go/src/github.com/wrouesnel/postgres_exporter/bin/"
    recurse: yes
    patterns: "postgres_exporter"
  register: findresult
  when: gitresult.changed

- name: "Copy postgres_exporter binary to /usr/local/bin"
  copy:
   src: "{{ findresult[0].path }}"
   dest: "/usr/local/bin/postgres_exporter"
   remote_src: yes
  when:
    - gitresult.changed

