---
- name: "Install freeradius3"
  pkgng:
    name: "freeradius3"
    state: "present"

- name: "Enable freeradius"
  service:
    name: "radiusd"
    enabled: yes

- name: "copy freeradius clients.conf into place"
  copy:
    owner: "freeradius"
    group: "freeradius"
    mode: "640"
    content: "{{ freeradius_clients_conf }}"
    dest: "/usr/local/etc/raddb/clients.conf"

- name: "Copy freeradius sql module config"
  template:
    src: "sql.j2"
    dest: "/usr/local/etc/raddb/mods-available/sql"
    owner: "freeradius"
    group: "freeradius"
    mode: "640"

- name: "Enable freeradius sql module"
  file:
    src: "/usr/local/etc/raddb/mods-available/sql"
    dest: "/usr/local/etc/raddb/mods-enabled/sql"
    state: "link"

- name: "Set DEFAULT Auth-Type to Accept in /usr/local/etc/mods-config/files/authorize"
  lineinfile:
    line: "DEFAULT Auth-Type := Accept"
    regexp: "^DEFAULT Auth-Type :="
    dest: "/usr/local/etc/mods-config/files/authorize"

