---
- name: "Copy nut_exporter binary"
  copy:
    src: "nut_exporter"
    dest: "/usr/local/bin/nut_exporter"
    owner: "root"
    group: "wheel"
    mode: "755"

- name: "Create supervisord.d config file to run nut_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "nut_exporter"
    supervisord_programs:
      - name: "nut_exporter"
        comment: "run nut_exporter"
        command: "/usr/local/bin/nut_exporter -ups {{ nut_ups_list.0.name }} -upsc /usr/local/bin/upsc"
        user: "nobody"
    supervisord_extra_programs: []

- name: "Create exporter_exporter.d config file for nut_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "nut_exporter.yml"
    expexp_program:
      method: "http"
      http:
        port: 8100
