---
- name: "Copy nut_exporter binary"
  copy:
    src: "nut_exporter"
    dest: "/usr/local/bin/nut_exporter"
    owner: "root"
    group: "wheel"
    mode: "755"

- name: "Create supervisord.d config file to run nut_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "nut_exporter_{{ ups_item.name }}"
    supervisord_programs:
      - name: "nut_exporter_{{ ups_item.name }}"
        comment: "run nut_exporter_{{ ups_item.name }}"
        command: "/usr/local/bin/nut_exporter -ups {{ ups_item.name }} -upsc /usr/local/bin/upsc -port {{ ups_idx + 8100 }}"
        user: "nobody"
    supervisord_extra_programs: []
  loop: "{{ nut_ups_list }}"
  loop_control:
    index_var: "ups_idx"
    loop_var: "ups_item"

- name: "Create exporter_exporter.d config file for nut_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "nut_exporter_{{ ups_item.name }}.yml"
    expexp_program:
      method: "http"
      http:
        port: "{{ ups_idx + 8100 | int }}"
  loop: "{{ nut_ups_list }}"
  loop_control:
    index_var: "ups_idx"
    loop_var: "ups_item"
