---
- name: "Enable dovecot"
  service:
    name: "dovecot"
    enabled: yes
  notify: "Reload dovecot"

- name: "Create certgrinder hooks.d file to reload dovecot"
  include_role:
    name: "certgrinder_client"
    tasks_from: "certgrinder_hook.d"
  vars:
    hookname: "dovecot"
    hookfile: |
      #!/bin/sh
      /usr/sbin/service dovecot reload
