---
- name: "Enable dovecot"
  service:
    name: "dovecot"
    enabled: yes
  notify: "Reload dovecot"

- name: "Create certgrinder hooks.d file to reload dovecot"
  include_role:
    name: "certgrinder_client"
    tasks_from: "certgrinder_hook.d"
  vars:
    hookname: "dovecot"
    hookfile: |
      #!/bin/sh
      /usr/sbin/service dovecot reload

- name: "Create exporter_exporter.d config file for dovecot"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "dovecot.yml"
    expexp_program:
      method: "http"
      http:
        port: 9900
