---
- name: "Remove old dovecot.log line from syslog.conf"
  lineinfile:
    dest: "/etc/syslog.conf"
    line: "local3.*                                        /var/log/dovecot.log"
    state: "absent"

- name: "Create dovecot.log if it doesn't exist"
  file:
    path: "/var/log/dovecot.log"
    state: "touch"
    mode: "600"
    modification_time: "preserve"
    access_time: "preserve"
  notify: "restart syslogd"

- name: "Remove old dovecot.log line from newsyslog.conf"
  lineinfile:
    dest: "/etc/newsyslog.conf"
    regexp: "^/var/log/dovecot.log "
    state: "absent"

- name: "make sure dovecot syslog.d config exists"
  template:
    src: "dovecot_syslog.conf.j2"
    dest: "/usr/local/etc/syslog.d/dovecot.conf"
  notify: "restart syslogd"

- name: "Make sure dovecot newsyslog config file exists"
  template:
    src: "dovecot_newsyslog.conf.j2"
    dest: "/usr/local/etc/newsyslog.conf.d/dovecot.conf"

